config/routes.rb
Rails.application.routes.draw do
  resources :epics

end

app/models/epic.rb
class Epic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController
  before_action :set_epic, only: [:show, :edit, :update, :destroy]

  # GET /epics
  # GET /epics.json
  def index
    @epics = Epic.all
  end

  # GET /epics/1
  # GET /epics/1.json
  def show
  end

  # GET /epics/new
  def new
    @epic = Epic.new
  end

  # GET /epics/1/edit
  def edit
  end

  # POST /epics
  # POST /epics.json
  def create
    @epic = Epic.new(epic_params)

    respond_to do |format|
      if @epic.save
        format.html { redirect_to @epic, notice: 'Epic was successfully created.' }
        format.json { render :show, status: :created, location: @epic }
      else
        format.html { render :new }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epics/1
  # PATCH/PUT /epics/1.json
  def update
    respond_to do |format|
      if @epic.update(epic_params)
        format.html { redirect_to @epic, notice: 'Epic was successfully updated.' }
        format.json { render :show, status: :ok, location: @epic }
      else
        format.html { render :edit }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epics/1
  # DELETE /epics/1.json
  def destroy
    @epic.destroy
    respond_to do |format|
      format.html { redirect_to epics_url, notice: 'Epic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epic
      @epic = Epic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epic_params
      params.require(:epic).permit(:rpt_date, :epic_key, :effort_tracking, :epic_name, :epic_component, :effort_original, :effort_remaining, :effort_spent, :effort_changed, :epic_reporter, :epic_type, :epic_assignee, :epic_status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epics_helper.rb
module EpicsHelper
end

app/views/epics/_form.html.erb
<%= form_for(@epic) do |f| %>
  <% if @epic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@epic.errors.count, "error") %> prohibited this epic from being saved:</h2>

      <ul>
      <% @epic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rpt_date %><br>
    <%= f.date_select :rpt_date %>
  </div>
  <div class="field">
    <%= f.label :epic_key %><br>
    <%= f.text_field :epic_key %>
  </div>
  <div class="field">
    <%= f.label :effort_tracking %><br>
    <%= f.text_field :effort_tracking %>
  </div>
  <div class="field">
    <%= f.label :epic_name %><br>
    <%= f.text_field :epic_name %>
  </div>
  <div class="field">
    <%= f.label :epic_component %><br>
    <%= f.text_field :epic_component %>
  </div>
  <div class="field">
    <%= f.label :effort_original %><br>
    <%= f.number_field :effort_original %>
  </div>
  <div class="field">
    <%= f.label :effort_remaining %><br>
    <%= f.number_field :effort_remaining %>
  </div>
  <div class="field">
    <%= f.label :effort_spent %><br>
    <%= f.number_field :effort_spent %>
  </div>
  <div class="field">
    <%= f.label :effort_changed %><br>
    <%= f.number_field :effort_changed %>
  </div>
  <div class="field">
    <%= f.label :epic_reporter %><br>
    <%= f.text_field :epic_reporter %>
  </div>
  <div class="field">
    <%= f.label :epic_type %><br>
    <%= f.text_field :epic_type %>
  </div>
  <div class="field">
    <%= f.label :epic_assignee %><br>
    <%= f.text_field :epic_assignee %>
  </div>
  <div class="field">
    <%= f.label :epic_status %><br>
    <%= f.text_field :epic_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/epics/edit.html.erb
<h1>Editing epic</h1>

<%= render 'form' %>

<%= link_to 'Show', @epic %> |
<%= link_to 'Back', epics_path %>

app/views/epics/index.html.erb
<h1>Listing epics</h1>

<table>
  <thead>
    <tr>
      <th>Rpt date</th>
      <th>Epic key</th>
      <th>Effort tracking</th>
      <th>Epic name</th>
      <th>Epic component</th>
      <th>Effort original</th>
      <th>Effort remaining</th>
      <th>Effort spent</th>
      <th>Effort changed</th>
      <th>Epic reporter</th>
      <th>Epic type</th>
      <th>Epic assignee</th>
      <th>Epic status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @epics.each do |epic| %>
      <tr>
        <td><%= epic.rpt_date %></td>
        <td><%= epic.epic_key %></td>
        <td><%= epic.effort_tracking %></td>
        <td><%= epic.epic_name %></td>
        <td><%= epic.epic_component %></td>
        <td><%= epic.effort_original %></td>
        <td><%= epic.effort_remaining %></td>
        <td><%= epic.effort_spent %></td>
        <td><%= epic.effort_changed %></td>
        <td><%= epic.epic_reporter %></td>
        <td><%= epic.epic_type %></td>
        <td><%= epic.epic_assignee %></td>
        <td><%= epic.epic_status %></td>
        <td><%= link_to 'Show', epic %></td>
        <td><%= link_to 'Edit', edit_epic_path(epic) %></td>
        <td><%= link_to 'Destroy', epic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Epic', new_epic_path %>

app/views/epics/new.html.erb
<h1>New epic</h1>

<%= render 'form' %>

<%= link_to 'Back', epics_path %>

app/views/epics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rpt date:</strong>
  <%= @epic.rpt_date %>
</p>

<p>
  <strong>Epic key:</strong>
  <%= @epic.epic_key %>
</p>

<p>
  <strong>Effort tracking:</strong>
  <%= @epic.effort_tracking %>
</p>

<p>
  <strong>Epic name:</strong>
  <%= @epic.epic_name %>
</p>

<p>
  <strong>Epic component:</strong>
  <%= @epic.epic_component %>
</p>

<p>
  <strong>Effort original:</strong>
  <%= @epic.effort_original %>
</p>

<p>
  <strong>Effort remaining:</strong>
  <%= @epic.effort_remaining %>
</p>

<p>
  <strong>Effort spent:</strong>
  <%= @epic.effort_spent %>
</p>

<p>
  <strong>Effort changed:</strong>
  <%= @epic.effort_changed %>
</p>

<p>
  <strong>Epic reporter:</strong>
  <%= @epic.epic_reporter %>
</p>

<p>
  <strong>Epic type:</strong>
  <%= @epic.epic_type %>
</p>

<p>
  <strong>Epic assignee:</strong>
  <%= @epic.epic_assignee %>
</p>

<p>
  <strong>Epic status:</strong>
  <%= @epic.epic_status %>
</p>

<%= link_to 'Edit', edit_epic_path(@epic) %> |
<%= link_to 'Back', epics_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Burndown</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>